FROM ssh

# --- docker build ---

RUN apt-get install -y software-properties-common python-software-properties

# Install Java.
RUN \
  echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java7-installer

# --- docker run ---
CMD ["/usr/sbin/sshd", "-D"]
